var exportar_1 = require("./exportar");
var exportar_2 = require("./exportar");
var paquete = require("./exportar");
console.log(exportar_1.PI);
console.log(paquete.PI);
var exportar_3 = require("./exportar");
exportar_3.saludar();
var deport = new exportar_3.Deportista();
deport.nombre = "PAU";
var futbol = { tieneBalon: true };
exportar_2.simple();
var default_1 = require("./default");
console.log(default_1["default"]);
default_1["default"].preguntar("TIenes pelo en la lengua?");
